# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_movimientos.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_movimientos(object):
    def setupUi(self, form_movimientos):
        form_movimientos.setObjectName("form_movimientos")
        form_movimientos.resize(563, 381)
        form_movimientos.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(117, 0, 88);")
        self.gridLayout_3 = QtWidgets.QGridLayout(form_movimientos)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(form_movimientos)
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(226, 226, 226);\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lne_compras_nro_fact = QtWidgets.QLineEdit(self.tab)
        self.lne_compras_nro_fact.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_compras_nro_fact.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_compras_nro_fact.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_compras_nro_fact.setText("")
        self.lne_compras_nro_fact.setObjectName("lne_compras_nro_fact")
        self.horizontalLayout_5.addWidget(self.lne_compras_nro_fact)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dte_compras_fec_factura = QtWidgets.QDateEdit(self.tab)
        self.dte_compras_fec_factura.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_compras_fec_factura.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_compras_fec_factura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_compras_fec_factura.setObjectName("dte_compras_fec_factura")
        self.horizontalLayout_5.addWidget(self.dte_compras_fec_factura)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.textEdit_compras = QtWidgets.QTextEdit(self.tab)
        self.textEdit_compras.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_compras.setObjectName("textEdit_compras")
        self.horizontalLayout_7.addWidget(self.textEdit_compras)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.ckbx_compras_coniva = QtWidgets.QCheckBox(self.tab)
        self.ckbx_compras_coniva.setMinimumSize(QtCore.QSize(0, 25))
        self.ckbx_compras_coniva.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ckbx_compras_coniva.setObjectName("ckbx_compras_coniva")
        self.verticalLayout_2.addWidget(self.ckbx_compras_coniva)
        self.ckbx_compras_coniva_2 = QtWidgets.QCheckBox(self.tab)
        self.ckbx_compras_coniva_2.setMinimumSize(QtCore.QSize(0, 25))
        self.ckbx_compras_coniva_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ckbx_compras_coniva_2.setObjectName("ckbx_compras_coniva_2")
        self.verticalLayout_2.addWidget(self.ckbx_compras_coniva_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.boton_compras = QtWidgets.QPushButton(self.tab)
        self.boton_compras.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_compras.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_compras.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_compras.setObjectName("boton_compras")
        self.gridLayout.addWidget(self.boton_compras, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lne_compras_total = QtWidgets.QLineEdit(self.tab)
        self.lne_compras_total.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_compras_total.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_compras_total.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_compras_total.setText("")
        self.lne_compras_total.setObjectName("lne_compras_total")
        self.horizontalLayout_6.addWidget(self.lne_compras_total)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.cbx_compras_concepto = QtWidgets.QComboBox(self.tab)
        self.cbx_compras_concepto.setMinimumSize(QtCore.QSize(0, 25))
        self.cbx_compras_concepto.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cbx_compras_concepto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_compras_concepto.setObjectName("cbx_compras_concepto")
        self.cbx_compras_concepto.addItem("")
        self.cbx_compras_concepto.addItem("")
        self.cbx_compras_concepto.addItem("")
        self.cbx_compras_concepto.addItem("")
        self.cbx_compras_concepto.addItem("")
        self.cbx_compras_concepto.addItem("")
        self.cbx_compras_concepto.addItem("")
        self.horizontalLayout_6.addWidget(self.cbx_compras_concepto)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lne_ventas_nro_fact = QtWidgets.QLineEdit(self.tab_2)
        self.lne_ventas_nro_fact.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_ventas_nro_fact.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_ventas_nro_fact.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_ventas_nro_fact.setText("")
        self.lne_ventas_nro_fact.setObjectName("lne_ventas_nro_fact")
        self.horizontalLayout.addWidget(self.lne_ventas_nro_fact)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.dte_ventas_fec_fact = QtWidgets.QDateEdit(self.tab_2)
        self.dte_ventas_fec_fact.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_ventas_fec_fact.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_ventas_fec_fact.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_ventas_fec_fact.setObjectName("dte_ventas_fec_fact")
        self.horizontalLayout.addWidget(self.dte_ventas_fec_fact)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lne_ventas_total = QtWidgets.QLineEdit(self.tab_2)
        self.lne_ventas_total.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_ventas_total.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_ventas_total.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_ventas_total.setText("")
        self.lne_ventas_total.setObjectName("lne_ventas_total")
        self.horizontalLayout_2.addWidget(self.lne_ventas_total)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.cbx_ventas_concepto = QtWidgets.QComboBox(self.tab_2)
        self.cbx_ventas_concepto.setMinimumSize(QtCore.QSize(0, 25))
        self.cbx_ventas_concepto.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cbx_ventas_concepto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_ventas_concepto.setObjectName("cbx_ventas_concepto")
        self.cbx_ventas_concepto.addItem("")
        self.cbx_ventas_concepto.addItem("")
        self.cbx_ventas_concepto.addItem("")
        self.cbx_ventas_concepto.addItem("")
        self.cbx_ventas_concepto.addItem("")
        self.cbx_ventas_concepto.addItem("")
        self.cbx_ventas_concepto.addItem("")
        self.horizontalLayout_2.addWidget(self.cbx_ventas_concepto)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.textEdit_ventas = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_ventas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_ventas.setObjectName("textEdit_ventas")
        self.horizontalLayout_3.addWidget(self.textEdit_ventas)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.ckbx_ventas_coniva = QtWidgets.QCheckBox(self.tab_2)
        self.ckbx_ventas_coniva.setMinimumSize(QtCore.QSize(0, 25))
        self.ckbx_ventas_coniva.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ckbx_ventas_coniva.setObjectName("ckbx_ventas_coniva")
        self.verticalLayout.addWidget(self.ckbx_ventas_coniva)
        self.ckbx_ventas_siniva = QtWidgets.QCheckBox(self.tab_2)
        self.ckbx_ventas_siniva.setMinimumSize(QtCore.QSize(0, 25))
        self.ckbx_ventas_siniva.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ckbx_ventas_siniva.setObjectName("ckbx_ventas_siniva")
        self.verticalLayout.addWidget(self.ckbx_ventas_siniva)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.boton_ventas = QtWidgets.QPushButton(self.tab_2)
        self.boton_ventas.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_ventas.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_ventas.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_ventas.setObjectName("boton_ventas")
        self.gridLayout_2.addWidget(self.boton_ventas, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(form_movimientos)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_movimientos)

    def retranslateUi(self, form_movimientos):
        _translate = QtCore.QCoreApplication.translate
        form_movimientos.setWindowTitle(_translate("form_movimientos", "Form"))
        self.label.setText(_translate("form_movimientos", "N° FACTURA: "))
        self.label_2.setText(_translate("form_movimientos", "FECHA:"))
        self.dte_compras_fec_factura.setDisplayFormat(_translate("form_movimientos", "dd/MM/yyyy"))
        self.label_9.setText(_translate("form_movimientos", "DETALLE:"))
        self.ckbx_compras_coniva.setText(_translate("form_movimientos", "c/ IVA"))
        self.ckbx_compras_coniva_2.setText(_translate("form_movimientos", "s/ IVA"))
        self.boton_compras.setText(_translate("form_movimientos", "Guardar"))
        self.label_4.setText(_translate("form_movimientos", "TOTAL:  $"))
        self.label_3.setText(_translate("form_movimientos", "CONCEPTO:"))
        self.cbx_compras_concepto.setItemText(0, _translate("form_movimientos", "Libreria"))
        self.cbx_compras_concepto.setItemText(1, _translate("form_movimientos", "New Item"))
        self.cbx_compras_concepto.setItemText(2, _translate("form_movimientos", "New Item"))
        self.cbx_compras_concepto.setItemText(3, _translate("form_movimientos", "New Item"))
        self.cbx_compras_concepto.setItemText(4, _translate("form_movimientos", "New Item"))
        self.cbx_compras_concepto.setItemText(5, _translate("form_movimientos", "New Item"))
        self.cbx_compras_concepto.setItemText(6, _translate("form_movimientos", "New Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_movimientos", "COMPRAS"))
        self.label_6.setText(_translate("form_movimientos", "N° FACTURA: "))
        self.label_5.setText(_translate("form_movimientos", "FECHA:"))
        self.dte_ventas_fec_fact.setDisplayFormat(_translate("form_movimientos", "dd/MM/yyyy"))
        self.label_7.setText(_translate("form_movimientos", "TOTAL:  $"))
        self.label_8.setText(_translate("form_movimientos", "CONCEPTO:"))
        self.cbx_ventas_concepto.setItemText(0, _translate("form_movimientos", "Libreria"))
        self.cbx_ventas_concepto.setItemText(1, _translate("form_movimientos", "New Item"))
        self.cbx_ventas_concepto.setItemText(2, _translate("form_movimientos", "New Item"))
        self.cbx_ventas_concepto.setItemText(3, _translate("form_movimientos", "New Item"))
        self.cbx_ventas_concepto.setItemText(4, _translate("form_movimientos", "New Item"))
        self.cbx_ventas_concepto.setItemText(5, _translate("form_movimientos", "New Item"))
        self.cbx_ventas_concepto.setItemText(6, _translate("form_movimientos", "New Item"))
        self.label_10.setText(_translate("form_movimientos", "DETALLE:"))
        self.ckbx_ventas_coniva.setText(_translate("form_movimientos", "c/ IVA"))
        self.ckbx_ventas_siniva.setText(_translate("form_movimientos", "s/ IVA"))
        self.boton_ventas.setText(_translate("form_movimientos", "Guardar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("form_movimientos", "VENTAS"))

