# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_cooperativa_alta.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_cooperativa_alta(object):
    def setupUi(self, form_cooperativa_alta):
        form_cooperativa_alta.setObjectName("form_cooperativa_alta")
        form_cooperativa_alta.resize(535, 497)
        form_cooperativa_alta.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(117, 0, 88);")
        self.gridLayout_3 = QtWidgets.QGridLayout(form_cooperativa_alta)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(form_cooperativa_alta)
        self.tabWidget_2.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lne_denominacion = QtWidgets.QLineEdit(self.tab_2)
        self.lne_denominacion.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_denominacion.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_denominacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_denominacion.setObjectName("lne_denominacion")
        self.horizontalLayout.addWidget(self.lne_denominacion)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lne_nro_matricula = QtWidgets.QLineEdit(self.tab_2)
        self.lne_nro_matricula.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_nro_matricula.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_nro_matricula.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_matricula.setText("")
        self.lne_nro_matricula.setObjectName("lne_nro_matricula")
        self.horizontalLayout_2.addWidget(self.lne_nro_matricula)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lne_nro_reg_prov = QtWidgets.QLineEdit(self.tab_2)
        self.lne_nro_reg_prov.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_nro_reg_prov.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_nro_reg_prov.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_reg_prov.setText("")
        self.lne_nro_reg_prov.setObjectName("lne_nro_reg_prov")
        self.horizontalLayout_2.addWidget(self.lne_nro_reg_prov)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.dte_inicio_actividades = QtWidgets.QDateEdit(self.tab_2)
        self.dte_inicio_actividades.setMinimumSize(QtCore.QSize(125, 25))
        self.dte_inicio_actividades.setMaximumSize(QtCore.QSize(125, 25))
        self.dte_inicio_actividades.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_inicio_actividades.setObjectName("dte_inicio_actividades")
        self.horizontalLayout_3.addWidget(self.dte_inicio_actividades)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lne_coope_cuit = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_cuit.setMinimumSize(QtCore.QSize(250, 25))
        self.lne_coope_cuit.setMaximumSize(QtCore.QSize(250, 25))
        self.lne_coope_cuit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_cuit.setText("")
        self.lne_coope_cuit.setObjectName("lne_coope_cuit")
        self.horizontalLayout_4.addWidget(self.lne_coope_cuit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.lne_coope_domicilio = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_domicilio.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_domicilio.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_domicilio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_domicilio.setObjectName("lne_coope_domicilio")
        self.horizontalLayout_5.addWidget(self.lne_coope_domicilio)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lne_coope_nro_dom = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_nro_dom.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_nro_dom.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_nro_dom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_nro_dom.setText("")
        self.lne_coope_nro_dom.setObjectName("lne_coope_nro_dom")
        self.horizontalLayout_5.addWidget(self.lne_coope_nro_dom)
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.lne_coope_piso = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_piso.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_piso.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_piso.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_piso.setText("")
        self.lne_coope_piso.setObjectName("lne_coope_piso")
        self.horizontalLayout_5.addWidget(self.lne_coope_piso)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        self.lne_coope_c_postal = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_c_postal.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_c_postal.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_c_postal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_c_postal.setText("")
        self.lne_coope_c_postal.setObjectName("lne_coope_c_postal")
        self.horizontalLayout_6.addWidget(self.lne_coope_c_postal)
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.lne_coope_localidad = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_localidad.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_localidad.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_localidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_localidad.setObjectName("lne_coope_localidad")
        self.horizontalLayout_6.addWidget(self.lne_coope_localidad)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_7.addWidget(self.label_29)
        self.lne_coope_provincia = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_provincia.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_provincia.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_provincia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_provincia.setObjectName("lne_coope_provincia")
        self.horizontalLayout_7.addWidget(self.lne_coope_provincia)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_8.addWidget(self.label_30)
        self.lne_coope_telefono = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_telefono.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_telefono.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_telefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_telefono.setObjectName("lne_coope_telefono")
        self.horizontalLayout_8.addWidget(self.lne_coope_telefono)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_9.addWidget(self.label_32)
        self.lne_coope_email = QtWidgets.QLineEdit(self.tab_2)
        self.lne_coope_email.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_coope_email.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_coope_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_coope_email.setObjectName("lne_coope_email")
        self.horizontalLayout_9.addWidget(self.lne_coope_email)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.line.raise_()
        self.lne_coope_cuit.raise_()
        self.lne_coope_provincia.raise_()
        self.tabWidget_2.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(form_cooperativa_alta)
        self.tabWidget.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.lne_cap_obliga = QtWidgets.QLineEdit(self.tab)
        self.lne_cap_obliga.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_cap_obliga.setObjectName("lne_cap_obliga")
        self.horizontalLayout_11.addWidget(self.lne_cap_obliga)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.lne_cant_cuotas = QtWidgets.QLineEdit(self.tab)
        self.lne_cant_cuotas.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lne_cant_cuotas.setObjectName("lne_cant_cuotas")
        self.horizontalLayout_12.addWidget(self.lne_cant_cuotas)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.boton_coope_actualizar = QtWidgets.QPushButton(form_cooperativa_alta)
        self.boton_coope_actualizar.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_coope_actualizar.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_coope_actualizar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_coope_actualizar.setObjectName("boton_coope_actualizar")
        self.horizontalLayout_13.addWidget(self.boton_coope_actualizar)
        self.boton_coope_guardar = QtWidgets.QPushButton(form_cooperativa_alta)
        self.boton_coope_guardar.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_coope_guardar.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_coope_guardar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_coope_guardar.setObjectName("boton_coope_guardar")
        self.horizontalLayout_13.addWidget(self.boton_coope_guardar)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)

        self.retranslateUi(form_cooperativa_alta)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_cooperativa_alta)

    def retranslateUi(self, form_cooperativa_alta):
        _translate = QtCore.QCoreApplication.translate
        form_cooperativa_alta.setWindowTitle(_translate("form_cooperativa_alta", "Datos de Entidad"))
        self.label.setText(_translate("form_cooperativa_alta", "Denominación:"))
        self.label_2.setText(_translate("form_cooperativa_alta", "Matrícula Nacional N°:"))
        self.label_3.setText(_translate("form_cooperativa_alta", "Reg. Provincial N°:"))
        self.label_4.setText(_translate("form_cooperativa_alta", "Inicio de actividades:"))
        self.dte_inicio_actividades.setDisplayFormat(_translate("form_cooperativa_alta", "dd/MM/yyyy"))
        self.label_5.setText(_translate("form_cooperativa_alta", "CUIT N°:"))
        self.label_10.setText(_translate("form_cooperativa_alta", "Domicilio:"))
        self.label_11.setText(_translate("form_cooperativa_alta", "N°:"))
        self.label_23.setText(_translate("form_cooperativa_alta", "Piso:"))
        self.label_27.setText(_translate("form_cooperativa_alta", "C.Postal:"))
        self.label_28.setText(_translate("form_cooperativa_alta", "Localidad:"))
        self.label_29.setText(_translate("form_cooperativa_alta", "Provincia:"))
        self.label_30.setText(_translate("form_cooperativa_alta", "Telefono :"))
        self.label_32.setText(_translate("form_cooperativa_alta", "Correo electrónico:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("form_cooperativa_alta", "Datos de la Entidad"))
        self.label_6.setText(_translate("form_cooperativa_alta", "Capital  minimo obligatorio :"))
        self.label_15.setText(_translate("form_cooperativa_alta", "Cantidad de cuotas:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_cooperativa_alta", "Configuración Contable de la Cooperativa"))
        self.boton_coope_actualizar.setText(_translate("form_cooperativa_alta", "Actualizar"))
        self.boton_coope_guardar.setText(_translate("form_cooperativa_alta", "GUARDAR"))

