# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_notas.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_notas(object):
    def setupUi(self, form_notas):
        form_notas.setObjectName("form_notas")
        form_notas.resize(660, 594)
        form_notas.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(117, 0, 88);")
        self.gridLayout_3 = QtWidgets.QGridLayout(form_notas)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(form_notas)
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(226, 226, 226);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lne_notas_titulo = QtWidgets.QLineEdit(self.tab)
        self.lne_notas_titulo.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_notas_titulo.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_notas_titulo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_notas_titulo.setObjectName("lne_notas_titulo")
        self.horizontalLayout.addWidget(self.lne_notas_titulo)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.dte_fec_notas = QtWidgets.QDateEdit(self.tab)
        self.dte_fec_notas.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_fec_notas.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_fec_notas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_notas.setObjectName("dte_fec_notas")
        self.horizontalLayout.addWidget(self.dte_fec_notas)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txt_detalle_notas = QtWidgets.QTextEdit(self.tab)
        self.txt_detalle_notas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_detalle_notas.setObjectName("txt_detalle_notas")
        self.verticalLayout.addWidget(self.txt_detalle_notas)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cbx_nota_tipo = QtWidgets.QComboBox(self.tab)
        self.cbx_nota_tipo.setMinimumSize(QtCore.QSize(0, 25))
        self.cbx_nota_tipo.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cbx_nota_tipo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_nota_tipo.setObjectName("cbx_nota_tipo")
        self.cbx_nota_tipo.addItem("")
        self.cbx_nota_tipo.addItem("")
        self.cbx_nota_tipo.addItem("")
        self.cbx_nota_tipo.addItem("")
        self.cbx_nota_tipo.addItem("")
        self.horizontalLayout_2.addWidget(self.cbx_nota_tipo)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.boton_notas_guardar = QtWidgets.QPushButton(self.tab)
        self.boton_notas_guardar.setMinimumSize(QtCore.QSize(0, 25))
        self.boton_notas_guardar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.boton_notas_guardar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_notas_guardar.setObjectName("boton_notas_guardar")
        self.gridLayout_2.addWidget(self.boton_notas_guardar, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_lista_notas = QtWidgets.QTableWidget(self.tab_2)
        self.tw_lista_notas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tw_lista_notas.setObjectName("tw_lista_notas")
        self.tw_lista_notas.setColumnCount(4)
        self.tw_lista_notas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_lista_notas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_lista_notas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_lista_notas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_lista_notas.setHorizontalHeaderItem(3, item)
        self.tw_lista_notas.horizontalHeader().setDefaultSectionSize(200)
        self.gridLayout.addWidget(self.tw_lista_notas, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.txt_notas_busqueda = QtWidgets.QTextEdit(self.tab_2)
        self.txt_notas_busqueda.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_notas_busqueda.setObjectName("txt_notas_busqueda")
        self.verticalLayout_2.addWidget(self.txt_notas_busqueda)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.boton_notas_imprimir = QtWidgets.QPushButton(self.tab_2)
        self.boton_notas_imprimir.setMinimumSize(QtCore.QSize(0, 25))
        self.boton_notas_imprimir.setMaximumSize(QtCore.QSize(16777215, 25))
        self.boton_notas_imprimir.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_notas_imprimir.setObjectName("boton_notas_imprimir")
        self.gridLayout.addWidget(self.boton_notas_imprimir, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(form_notas)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_notas)

    def retranslateUi(self, form_notas):
        _translate = QtCore.QCoreApplication.translate
        form_notas.setWindowTitle(_translate("form_notas", "Form"))
        self.label.setText(_translate("form_notas", "Título:"))
        self.label_4.setText(_translate("form_notas", "Fecha:"))
        self.dte_fec_notas.setDisplayFormat(_translate("form_notas", "dd/MM/yyyy"))
        self.label_2.setText(_translate("form_notas", "Detalle:"))
        self.label_3.setText(_translate("form_notas", "Tipo de nota:"))
        self.cbx_nota_tipo.setItemText(0, _translate("form_notas", "Informe de auditoría"))
        self.cbx_nota_tipo.setItemText(1, _translate("form_notas", "Reunión C.A"))
        self.cbx_nota_tipo.setItemText(2, _translate("form_notas", "Informe de sindicatura"))
        self.cbx_nota_tipo.setItemText(3, _translate("form_notas", "Actas de asambleas"))
        self.cbx_nota_tipo.setItemText(4, _translate("form_notas", "Otros"))
        self.boton_notas_guardar.setText(_translate("form_notas", "Guardar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_notas", "Notas e informes"))
        item = self.tw_lista_notas.horizontalHeaderItem(0)
        item.setText(_translate("form_notas", "Titulo"))
        item = self.tw_lista_notas.horizontalHeaderItem(1)
        item.setText(_translate("form_notas", "Fecha"))
        item = self.tw_lista_notas.horizontalHeaderItem(2)
        item.setText(_translate("form_notas", "Detalle"))
        item = self.tw_lista_notas.horizontalHeaderItem(3)
        item.setText(_translate("form_notas", "Tipo Nota"))
        self.label_5.setText(_translate("form_notas", "Detalle:"))
        self.boton_notas_imprimir.setText(_translate("form_notas", "Imprimir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("form_notas", "Listado de Notas"))

