# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_asociado_actualizar.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_asociado_actualizar(object):
    def setupUi(self, form_asociado_actualizar):
        form_asociado_actualizar.setObjectName("form_asociado_actualizar")
        form_asociado_actualizar.resize(750, 675)
        form_asociado_actualizar.setMinimumSize(QtCore.QSize(750, 675))
        form_asociado_actualizar.setMaximumSize(QtCore.QSize(750, 675))
        form_asociado_actualizar.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"background-color: rgb(131, 45, 108);\n"
"color: rgb(0, 0, 0);")
        self.gridLayout_7 = QtWidgets.QGridLayout(form_asociado_actualizar)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(form_asociado_actualizar)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_29.addWidget(self.label_12)
        self.lne_buscar_nro_asoc = QtWidgets.QLineEdit(self.frame)
        self.lne_buscar_nro_asoc.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_buscar_nro_asoc.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_buscar_nro_asoc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_buscar_nro_asoc.setObjectName("lne_buscar_nro_asoc")
        self.horizontalLayout_29.addWidget(self.lne_buscar_nro_asoc)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_29.addWidget(self.label_14)
        self.lne_buscar_nro_doc = QtWidgets.QLineEdit(self.frame)
        self.lne_buscar_nro_doc.setMinimumSize(QtCore.QSize(250, 25))
        self.lne_buscar_nro_doc.setMaximumSize(QtCore.QSize(250, 25))
        self.lne_buscar_nro_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_buscar_nro_doc.setText("")
        self.lne_buscar_nro_doc.setObjectName("lne_buscar_nro_doc")
        self.horizontalLayout_29.addWidget(self.lne_buscar_nro_doc)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30.addLayout(self.verticalLayout_2)
        self.boton_buscar = QtWidgets.QPushButton(self.frame)
        self.boton_buscar.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_buscar.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_buscar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_buscar.setObjectName("boton_buscar")
        self.horizontalLayout_30.addWidget(self.boton_buscar)
        self.gridLayout_6.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.line_2 = QtWidgets.QFrame(form_asociado_actualizar)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(form_asociado_actualizar)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(226, 226, 226);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(100, 25))
        self.label_6.setMaximumSize(QtCore.QSize(100, 25))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cbx_tipo_doc = QtWidgets.QComboBox(self.tab)
        self.cbx_tipo_doc.setMinimumSize(QtCore.QSize(65, 25))
        self.cbx_tipo_doc.setMaximumSize(QtCore.QSize(65, 25))
        self.cbx_tipo_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_tipo_doc.setObjectName("cbx_tipo_doc")
        self.cbx_tipo_doc.addItem("")
        self.cbx_tipo_doc.addItem("")
        self.cbx_tipo_doc.addItem("")
        self.cbx_tipo_doc.addItem("")
        self.horizontalLayout_6.addWidget(self.cbx_tipo_doc)
        self.lne_nro_doc = QtWidgets.QLineEdit(self.tab)
        self.lne_nro_doc.setMinimumSize(QtCore.QSize(125, 25))
        self.lne_nro_doc.setMaximumSize(QtCore.QSize(125, 25))
        self.lne_nro_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_doc.setText("")
        self.lne_nro_doc.setObjectName("lne_nro_doc")
        self.horizontalLayout_6.addWidget(self.lne_nro_doc)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(125, 25))
        self.label_5.setMaximumSize(QtCore.QSize(125, 25))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.cbx_estado_civil = QtWidgets.QComboBox(self.tab)
        self.cbx_estado_civil.setMinimumSize(QtCore.QSize(110, 25))
        self.cbx_estado_civil.setMaximumSize(QtCore.QSize(100, 25))
        self.cbx_estado_civil.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_estado_civil.setObjectName("cbx_estado_civil")
        self.cbx_estado_civil.addItem("")
        self.cbx_estado_civil.addItem("")
        self.cbx_estado_civil.addItem("")
        self.cbx_estado_civil.addItem("")
        self.cbx_estado_civil.addItem("")
        self.horizontalLayout_9.addWidget(self.cbx_estado_civil)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_9, 5, 1, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(116, 25))
        self.label_8.setMaximumSize(QtCore.QSize(116, 25))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lne_nro_cuil = QtWidgets.QLineEdit(self.tab)
        self.lne_nro_cuil.setMinimumSize(QtCore.QSize(150, 25))
        self.lne_nro_cuil.setMaximumSize(QtCore.QSize(150, 25))
        self.lne_nro_cuil.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_cuil.setText("")
        self.lne_nro_cuil.setObjectName("lne_nro_cuil")
        self.horizontalLayout_7.addWidget(self.lne_nro_cuil)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 1, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 10, 0, 1, 3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setMinimumSize(QtCore.QSize(100, 25))
        self.label_28.setMaximumSize(QtCore.QSize(100, 25))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.lne_localidad = QtWidgets.QLineEdit(self.tab)
        self.lne_localidad.setMinimumSize(QtCore.QSize(150, 25))
        self.lne_localidad.setMaximumSize(QtCore.QSize(150, 25))
        self.lne_localidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_localidad.setObjectName("lne_localidad")
        self.horizontalLayout_12.addWidget(self.lne_localidad)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setMinimumSize(QtCore.QSize(100, 25))
        self.label_29.setMaximumSize(QtCore.QSize(100, 25))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.lne_provincia = QtWidgets.QLineEdit(self.tab)
        self.lne_provincia.setMinimumSize(QtCore.QSize(150, 25))
        self.lne_provincia.setMaximumSize(QtCore.QSize(150, 25))
        self.lne_provincia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_provincia.setObjectName("lne_provincia")
        self.horizontalLayout_12.addWidget(self.lne_provincia)
        self.gridLayout.addLayout(self.horizontalLayout_12, 9, 0, 1, 3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(200, 25))
        self.label_7.setMaximumSize(QtCore.QSize(200, 25))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.dte_fec_nac = QtWidgets.QDateEdit(self.tab)
        self.dte_fec_nac.setMinimumSize(QtCore.QSize(120, 25))
        self.dte_fec_nac.setMaximumSize(QtCore.QSize(100, 25))
        self.dte_fec_nac.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_nac.setObjectName("dte_fec_nac")
        self.horizontalLayout_8.addWidget(self.dte_fec_nac)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_8, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(100, 25))
        self.label_10.setMaximumSize(QtCore.QSize(100, 25))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10, 0, QtCore.Qt.AlignLeft)
        self.lne_domicilio = QtWidgets.QLineEdit(self.tab)
        self.lne_domicilio.setMinimumSize(QtCore.QSize(170, 25))
        self.lne_domicilio.setMaximumSize(QtCore.QSize(125, 25))
        self.lne_domicilio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_domicilio.setObjectName("lne_domicilio")
        self.horizontalLayout_10.addWidget(self.lne_domicilio)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMinimumSize(QtCore.QSize(50, 25))
        self.label_11.setMaximumSize(QtCore.QSize(50, 25))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.lne_nro_dom = QtWidgets.QLineEdit(self.tab)
        self.lne_nro_dom.setMinimumSize(QtCore.QSize(70, 25))
        self.lne_nro_dom.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_nro_dom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_dom.setText("")
        self.lne_nro_dom.setObjectName("lne_nro_dom")
        self.horizontalLayout_10.addWidget(self.lne_nro_dom)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setMinimumSize(QtCore.QSize(75, 25))
        self.label_23.setMaximumSize(QtCore.QSize(75, 25))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.lne_piso_domicilio = QtWidgets.QLineEdit(self.tab)
        self.lne_piso_domicilio.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_piso_domicilio.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_piso_domicilio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_piso_domicilio.setText("")
        self.lne_piso_domicilio.setObjectName("lne_piso_domicilio")
        self.horizontalLayout_10.addWidget(self.lne_piso_domicilio)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_10, 7, 0, 1, 3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lne_apellido_2 = QtWidgets.QLineEdit(self.tab)
        self.lne_apellido_2.setMinimumSize(QtCore.QSize(220, 25))
        self.lne_apellido_2.setMaximumSize(QtCore.QSize(250, 25))
        self.lne_apellido_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_apellido_2.setObjectName("lne_apellido_2")
        self.horizontalLayout_5.addWidget(self.lne_apellido_2)
        self.lne_nombre_2 = QtWidgets.QLineEdit(self.tab)
        self.lne_nombre_2.setMinimumSize(QtCore.QSize(160, 25))
        self.lne_nombre_2.setMaximumSize(QtCore.QSize(250, 25))
        self.lne_nombre_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nombre_2.setObjectName("lne_nombre_2")
        self.horizontalLayout_5.addWidget(self.lne_nombre_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.cbx_estado_asoc = QtWidgets.QComboBox(self.tab)
        self.cbx_estado_asoc.setMinimumSize(QtCore.QSize(100, 25))
        self.cbx_estado_asoc.setMaximumSize(QtCore.QSize(100, 25))
        self.cbx_estado_asoc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_estado_asoc.setObjectName("cbx_estado_asoc")
        self.cbx_estado_asoc.addItem("")
        self.cbx_estado_asoc.addItem("")
        self.cbx_estado_asoc.addItem("")
        self.cbx_estado_asoc.addItem("")
        self.horizontalLayout_5.addWidget(self.cbx_estado_asoc)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setMinimumSize(QtCore.QSize(200, 25))
        self.label_30.setMaximumSize(QtCore.QSize(200, 25))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_13.addWidget(self.label_30)
        self.lne_tel_principal = QtWidgets.QLineEdit(self.tab)
        self.lne_tel_principal.setMinimumSize(QtCore.QSize(200, 25))
        self.lne_tel_principal.setMaximumSize(QtCore.QSize(200, 25))
        self.lne_tel_principal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_tel_principal.setObjectName("lne_tel_principal")
        self.horizontalLayout_13.addWidget(self.lne_tel_principal)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setMinimumSize(QtCore.QSize(200, 25))
        self.label_31.setMaximumSize(QtCore.QSize(200, 25))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_14.addWidget(self.label_31)
        self.lne_tel_otro = QtWidgets.QLineEdit(self.tab)
        self.lne_tel_otro.setMinimumSize(QtCore.QSize(200, 25))
        self.lne_tel_otro.setMaximumSize(QtCore.QSize(200, 25))
        self.lne_tel_otro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_tel_otro.setObjectName("lne_tel_otro")
        self.horizontalLayout_14.addWidget(self.lne_tel_otro)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setMinimumSize(QtCore.QSize(200, 25))
        self.label_32.setMaximumSize(QtCore.QSize(200, 25))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_15.addWidget(self.label_32)
        self.lne_correo = QtWidgets.QLineEdit(self.tab)
        self.lne_correo.setMinimumSize(QtCore.QSize(200, 25))
        self.lne_correo.setMaximumSize(QtCore.QSize(200, 25))
        self.lne_correo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_correo.setObjectName("lne_correo")
        self.horizontalLayout_15.addWidget(self.lne_correo)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem12)
        self.boton_actualizar = QtWidgets.QPushButton(self.tab)
        self.boton_actualizar.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_actualizar.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_actualizar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_actualizar.setObjectName("boton_actualizar")
        self.horizontalLayout_26.addWidget(self.boton_actualizar)
        self.boton_limpiar = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.boton_limpiar.sizePolicy().hasHeightForWidth())
        self.boton_limpiar.setSizePolicy(sizePolicy)
        self.boton_limpiar.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_limpiar.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_limpiar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_limpiar.setObjectName("boton_limpiar")
        self.horizontalLayout_26.addWidget(self.boton_limpiar)
        self.gridLayout_2.addLayout(self.horizontalLayout_26, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 11, 0, 1, 3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setMinimumSize(QtCore.QSize(50, 25))
        self.label_24.setMaximumSize(QtCore.QSize(50, 25))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.lne_depto = QtWidgets.QLineEdit(self.tab)
        self.lne_depto.setMinimumSize(QtCore.QSize(60, 25))
        self.lne_depto.setMaximumSize(QtCore.QSize(60, 25))
        self.lne_depto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_depto.setText("")
        self.lne_depto.setObjectName("lne_depto")
        self.horizontalLayout_11.addWidget(self.lne_depto)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setMinimumSize(QtCore.QSize(80, 25))
        self.label_25.setMaximumSize(QtCore.QSize(80, 25))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.lne_bloque = QtWidgets.QLineEdit(self.tab)
        self.lne_bloque.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_bloque.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_bloque.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_bloque.setText("")
        self.lne_bloque.setObjectName("lne_bloque")
        self.horizontalLayout_11.addWidget(self.lne_bloque)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setMinimumSize(QtCore.QSize(51, 25))
        self.label_26.setMaximumSize(QtCore.QSize(51, 25))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_11.addWidget(self.label_26)
        self.lne_mzna = QtWidgets.QLineEdit(self.tab)
        self.lne_mzna.setMinimumSize(QtCore.QSize(60, 25))
        self.lne_mzna.setMaximumSize(QtCore.QSize(60, 25))
        self.lne_mzna.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_mzna.setText("")
        self.lne_mzna.setObjectName("lne_mzna")
        self.horizontalLayout_11.addWidget(self.lne_mzna)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setMinimumSize(QtCore.QSize(91, 25))
        self.label_27.setMaximumSize(QtCore.QSize(91, 25))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_11.addWidget(self.label_27)
        self.lne_c_postal = QtWidgets.QLineEdit(self.tab)
        self.lne_c_postal.setMinimumSize(QtCore.QSize(60, 25))
        self.lne_c_postal.setMaximumSize(QtCore.QSize(60, 25))
        self.lne_c_postal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_c_postal.setText("")
        self.lne_c_postal.setObjectName("lne_c_postal")
        self.horizontalLayout_11.addWidget(self.lne_c_postal)
        self.gridLayout.addLayout(self.horizontalLayout_11, 8, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(135, 25))
        self.label_2.setMaximumSize(QtCore.QSize(135, 25))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.dte_ingreso = QtWidgets.QDateEdit(self.tab)
        self.dte_ingreso.setMinimumSize(QtCore.QSize(125, 25))
        self.dte_ingreso.setMaximumSize(QtCore.QSize(125, 25))
        self.dte_ingreso.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_ingreso.setObjectName("dte_ingreso")
        self.horizontalLayout_4.addWidget(self.dte_ingreso)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(125, 25))
        self.label_3.setMaximumSize(QtCore.QSize(125, 25))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lne_nro_acta_ca = QtWidgets.QLineEdit(self.tab)
        self.lne_nro_acta_ca.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_nro_acta_ca.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_nro_acta_ca.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_acta_ca.setObjectName("lne_nro_acta_ca")
        self.horizontalLayout_4.addWidget(self.lne_nro_acta_ca)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(125, 25))
        self.label.setMaximumSize(QtCore.QSize(125, 25))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.lne_nro_asoc = QtWidgets.QLineEdit(self.tab)
        self.lne_nro_asoc.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_nro_asoc.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_nro_asoc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_asoc.setObjectName("lne_nro_asoc")
        self.horizontalLayout.addWidget(self.lne_nro_asoc, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMinimumSize(QtCore.QSize(80, 25))
        self.label_9.setMaximumSize(QtCore.QSize(80, 25))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lne_nro_foja = QtWidgets.QLineEdit(self.tab)
        self.lne_nro_foja.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_nro_foja.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_nro_foja.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_foja.setObjectName("lne_nro_foja")
        self.horizontalLayout_2.addWidget(self.lne_nro_foja)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"text-decoration: underline;")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_27.addWidget(self.label_33)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem15)
        self.boton_actualizar_cap_suscripto = QtWidgets.QPushButton(self.tab_3)
        self.boton_actualizar_cap_suscripto.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_cap_suscripto.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_cap_suscripto.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"\n"
"color: rgb(0, 0, 0);")
        self.boton_actualizar_cap_suscripto.setObjectName("boton_actualizar_cap_suscripto")
        self.horizontalLayout_27.addWidget(self.boton_actualizar_cap_suscripto)
        self.gridLayout_3.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_16.addWidget(self.label_34)
        self.lne_asamble_cap_sus = QtWidgets.QLineEdit(self.tab_3)
        self.lne_asamble_cap_sus.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_asamble_cap_sus.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_asamble_cap_sus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_asamble_cap_sus.setObjectName("lne_asamble_cap_sus")
        self.horizontalLayout_16.addWidget(self.lne_asamble_cap_sus)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem17)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_16.addWidget(self.label_35)
        self.dte_fec_asamblea_cap_sus = QtWidgets.QDateEdit(self.tab_3)
        self.dte_fec_asamblea_cap_sus.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_fec_asamblea_cap_sus.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_fec_asamblea_cap_sus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_asamblea_cap_sus.setObjectName("dte_fec_asamblea_cap_sus")
        self.horizontalLayout_16.addWidget(self.dte_fec_asamblea_cap_sus)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setMinimumSize(QtCore.QSize(210, 25))
        self.label_36.setMaximumSize(QtCore.QSize(210, 25))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_17.addWidget(self.label_36)
        self.lne_cant_cta_soc_cap_sus = QtWidgets.QLineEdit(self.tab_3)
        self.lne_cant_cta_soc_cap_sus.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_cant_cta_soc_cap_sus.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_cant_cta_soc_cap_sus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cant_cta_soc_cap_sus.setText("")
        self.lne_cant_cta_soc_cap_sus.setObjectName("lne_cant_cta_soc_cap_sus")
        self.horizontalLayout_17.addWidget(self.lne_cant_cta_soc_cap_sus)
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setMinimumSize(QtCore.QSize(150, 25))
        self.label_37.setMaximumSize(QtCore.QSize(150, 25))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_17.addWidget(self.label_37)
        self.lne_pesos_cap_sus = QtWidgets.QLineEdit(self.tab_3)
        self.lne_pesos_cap_sus.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_pesos_cap_sus.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_pesos_cap_sus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_pesos_cap_sus.setText("")
        self.lne_pesos_cap_sus.setObjectName("lne_pesos_cap_sus")
        self.horizontalLayout_17.addWidget(self.lne_pesos_cap_sus)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem18)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_18.addWidget(self.label_38)
        self.lne_pesos_letras_cap_sus = QtWidgets.QLineEdit(self.tab_3)
        self.lne_pesos_letras_cap_sus.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_pesos_letras_cap_sus.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_pesos_letras_cap_sus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_pesos_letras_cap_sus.setText("")
        self.lne_pesos_letras_cap_sus.setObjectName("lne_pesos_letras_cap_sus")
        self.horizontalLayout_18.addWidget(self.lne_pesos_letras_cap_sus)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 4, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"text-decoration: underline;")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_28.addWidget(self.label_39)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem19)
        self.boton_act_cap_integracion = QtWidgets.QPushButton(self.tab_3)
        self.boton_act_cap_integracion.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_act_cap_integracion.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_act_cap_integracion.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"color: rgb(0, 0, 0);")
        self.boton_act_cap_integracion.setObjectName("boton_act_cap_integracion")
        self.horizontalLayout_28.addWidget(self.boton_act_cap_integracion)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 5, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        self.label_40.setMinimumSize(QtCore.QSize(106, 25))
        self.label_40.setMaximumSize(QtCore.QSize(106, 25))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_19.addWidget(self.label_40)
        self.lne_nro_cuota = QtWidgets.QLineEdit(self.tab_3)
        self.lne_nro_cuota.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_nro_cuota.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_nro_cuota.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_cuota.setObjectName("lne_nro_cuota")
        self.horizontalLayout_19.addWidget(self.lne_nro_cuota)
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setMinimumSize(QtCore.QSize(75, 25))
        self.label_41.setMaximumSize(QtCore.QSize(75, 25))
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_19.addWidget(self.label_41)
        self.dte_fec_cuota = QtWidgets.QDateEdit(self.tab_3)
        self.dte_fec_cuota.setMinimumSize(QtCore.QSize(125, 25))
        self.dte_fec_cuota.setMaximumSize(QtCore.QSize(125, 25))
        self.dte_fec_cuota.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_cuota.setObjectName("dte_fec_cuota")
        self.horizontalLayout_19.addWidget(self.dte_fec_cuota)
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setMinimumSize(QtCore.QSize(60, 25))
        self.label_42.setMaximumSize(QtCore.QSize(60, 25))
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_19.addWidget(self.label_42)
        self.lne_importe_cta = QtWidgets.QLineEdit(self.tab_3)
        self.lne_importe_cta.setMinimumSize(QtCore.QSize(75, 25))
        self.lne_importe_cta.setMaximumSize(QtCore.QSize(75, 25))
        self.lne_importe_cta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_importe_cta.setText("")
        self.lne_importe_cta.setObjectName("lne_importe_cta")
        self.horizontalLayout_19.addWidget(self.lne_importe_cta)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem20)
        self.btn_pagar = QtWidgets.QPushButton(self.tab_3)
        self.btn_pagar.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"color: rgb(0, 0, 0);")
        self.btn_pagar.setObjectName("btn_pagar")
        self.horizontalLayout_19.addWidget(self.btn_pagar)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 6, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_20.addWidget(self.label_43)
        self.cbx_aporte_tipo = QtWidgets.QComboBox(self.tab_3)
        self.cbx_aporte_tipo.setMinimumSize(QtCore.QSize(120, 25))
        self.cbx_aporte_tipo.setMaximumSize(QtCore.QSize(150, 25))
        self.cbx_aporte_tipo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_aporte_tipo.setObjectName("cbx_aporte_tipo")
        self.cbx_aporte_tipo.addItem("")
        self.cbx_aporte_tipo.addItem("")
        self.horizontalLayout_20.addWidget(self.cbx_aporte_tipo)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem21)
        self.boton_agregar = QtWidgets.QPushButton(self.tab_3)
        self.boton_agregar.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_agregar.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_agregar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_agregar.setObjectName("boton_agregar")
        self.horizontalLayout_20.addWidget(self.boton_agregar)
        self.gridLayout_3.addLayout(self.horizontalLayout_20, 7, 0, 1, 1)
        self.tw_integracion_cap = QtWidgets.QTableWidget(self.tab_3)
        self.tw_integracion_cap.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.tw_integracion_cap.setObjectName("tw_integracion_cap")
        self.tw_integracion_cap.setColumnCount(6)
        self.tw_integracion_cap.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_integracion_cap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_integracion_cap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_integracion_cap.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_integracion_cap.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_integracion_cap.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_integracion_cap.setHorizontalHeaderItem(5, item)
        self.tw_integracion_cap.horizontalHeader().setDefaultSectionSize(200)
        self.tw_integracion_cap.horizontalHeader().setMinimumSectionSize(200)
        self.tw_integracion_cap.verticalHeader().setDefaultSectionSize(15)
        self.gridLayout_3.addWidget(self.tw_integracion_cap, 8, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setMinimumSize(QtCore.QSize(250, 25))
        self.label_44.setMaximumSize(QtCore.QSize(250, 25))
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_21.addWidget(self.label_44)
        self.lne_transf_cuotas = QtWidgets.QLineEdit(self.tab_3)
        self.lne_transf_cuotas.setMinimumSize(QtCore.QSize(200, 25))
        self.lne_transf_cuotas.setMaximumSize(QtCore.QSize(200, 25))
        self.lne_transf_cuotas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_transf_cuotas.setText("")
        self.lne_transf_cuotas.setObjectName("lne_transf_cuotas")
        self.horizontalLayout_21.addWidget(self.lne_transf_cuotas)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem22)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 9, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        self.label_45.setMinimumSize(QtCore.QSize(125, 25))
        self.label_45.setMaximumSize(QtCore.QSize(125, 25))
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_22.addWidget(self.label_45)
        self.lne_cant_ctas_transf = QtWidgets.QLineEdit(self.tab_3)
        self.lne_cant_ctas_transf.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_cant_ctas_transf.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_cant_ctas_transf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cant_ctas_transf.setText("")
        self.lne_cant_ctas_transf.setObjectName("lne_cant_ctas_transf")
        self.horizontalLayout_22.addWidget(self.lne_cant_ctas_transf)
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        self.label_46.setMinimumSize(QtCore.QSize(120, 25))
        self.label_46.setMaximumSize(QtCore.QSize(120, 25))
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_22.addWidget(self.label_46)
        self.lne_monto_transf = QtWidgets.QLineEdit(self.tab_3)
        self.lne_monto_transf.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_monto_transf.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_monto_transf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_monto_transf.setText("")
        self.lne_monto_transf.setObjectName("lne_monto_transf")
        self.horizontalLayout_22.addWidget(self.lne_monto_transf)
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setMinimumSize(QtCore.QSize(75, 25))
        self.label_47.setMaximumSize(QtCore.QSize(75, 25))
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_22.addWidget(self.label_47)
        self.dte_fec_transf = QtWidgets.QDateEdit(self.tab_3)
        self.dte_fec_transf.setMinimumSize(QtCore.QSize(125, 25))
        self.dte_fec_transf.setMaximumSize(QtCore.QSize(125, 25))
        self.dte_fec_transf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_transf.setObjectName("dte_fec_transf")
        self.horizontalLayout_22.addWidget(self.dte_fec_transf)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem23)
        self.gridLayout_3.addLayout(self.horizontalLayout_22, 10, 0, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        self.label_48.setMinimumSize(QtCore.QSize(125, 25))
        self.label_48.setMaximumSize(QtCore.QSize(125, 25))
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_23.addWidget(self.label_48)
        self.lne_nro_acta_transf = QtWidgets.QLineEdit(self.tab_3)
        self.lne_nro_acta_transf.setMinimumSize(QtCore.QSize(50, 25))
        self.lne_nro_acta_transf.setMaximumSize(QtCore.QSize(50, 25))
        self.lne_nro_acta_transf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_acta_transf.setObjectName("lne_nro_acta_transf")
        self.horizontalLayout_23.addWidget(self.lne_nro_acta_transf)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem24)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_23)
        self.boton_guardar_transferencia_2 = QtWidgets.QPushButton(self.tab_3)
        self.boton_guardar_transferencia_2.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_guardar_transferencia_2.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_guardar_transferencia_2.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"color: rgb(0, 0, 0);")
        self.boton_guardar_transferencia_2.setObjectName("boton_guardar_transferencia_2")
        self.horizontalLayout_31.addWidget(self.boton_guardar_transferencia_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_31, 11, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_49 = QtWidgets.QLabel(self.tab_4)
        self.label_49.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"text-decoration: underline;")
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_34.addWidget(self.label_49)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem25)
        self.boton_guardar_suspenciones = QtWidgets.QPushButton(self.tab_4)
        self.boton_guardar_suspenciones.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_guardar_suspenciones.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_guardar_suspenciones.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"color: rgb(0, 0, 0);")
        self.boton_guardar_suspenciones.setObjectName("boton_guardar_suspenciones")
        self.horizontalLayout_34.addWidget(self.boton_guardar_suspenciones)
        self.gridLayout_4.addLayout(self.horizontalLayout_34, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_52 = QtWidgets.QLabel(self.tab_4)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_24.addWidget(self.label_52)
        self.dte_fec_susp = QtWidgets.QDateEdit(self.tab_4)
        self.dte_fec_susp.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_fec_susp.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_fec_susp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_susp.setObjectName("dte_fec_susp")
        self.horizontalLayout_24.addWidget(self.dte_fec_susp)
        self.label_53 = QtWidgets.QLabel(self.tab_4)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_24.addWidget(self.label_53)
        self.lne_nro_acta_susp = QtWidgets.QLineEdit(self.tab_4)
        self.lne_nro_acta_susp.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_nro_acta_susp.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_nro_acta_susp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_acta_susp.setObjectName("lne_nro_acta_susp")
        self.horizontalLayout_24.addWidget(self.lne_nro_acta_susp)
        self.gridLayout_4.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_54 = QtWidgets.QLabel(self.tab_4)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_25.addWidget(self.label_54)
        self.txt_detalle_susp = QtWidgets.QTextEdit(self.tab_4)
        self.txt_detalle_susp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_detalle_susp.setObjectName("txt_detalle_susp")
        self.horizontalLayout_25.addWidget(self.txt_detalle_susp)
        self.boton_agregar_suspensiones = QtWidgets.QPushButton(self.tab_4)
        self.boton_agregar_suspensiones.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_agregar_suspensiones.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_agregar_suspensiones.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_agregar_suspensiones.setObjectName("boton_agregar_suspensiones")
        self.horizontalLayout_25.addWidget(self.boton_agregar_suspensiones)
        self.gridLayout_4.addLayout(self.horizontalLayout_25, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tw_historia_susp = QtWidgets.QTableWidget(self.tab_4)
        self.tw_historia_susp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Courier 10 Pitch\";")
        self.tw_historia_susp.setObjectName("tw_historia_susp")
        self.tw_historia_susp.setColumnCount(4)
        self.tw_historia_susp.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(202, 244, 175))
        self.tw_historia_susp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(202, 244, 175))
        self.tw_historia_susp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(202, 244, 175))
        self.tw_historia_susp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_historia_susp.setHorizontalHeaderItem(3, item)
        self.tw_historia_susp.horizontalHeader().setDefaultSectionSize(250)
        self.tw_historia_susp.verticalHeader().setDefaultSectionSize(15)
        self.verticalLayout.addWidget(self.tw_historia_susp)
        self.line_5 = QtWidgets.QFrame(self.tab_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.gridLayout_4.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"text-decoration: underline;")
        self.label_50.setObjectName("label_50")
        self.verticalLayout_3.addWidget(self.label_50)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_99 = QtWidgets.QLabel(self.tab_4)
        self.label_99.setObjectName("label_99")
        self.horizontalLayout_32.addWidget(self.label_99)
        self.dte_fec_renuncia = QtWidgets.QDateEdit(self.tab_4)
        self.dte_fec_renuncia.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_fec_renuncia.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_fec_renuncia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_renuncia.setObjectName("dte_fec_renuncia")
        self.horizontalLayout_32.addWidget(self.dte_fec_renuncia)
        self.label_98 = QtWidgets.QLabel(self.tab_4)
        self.label_98.setObjectName("label_98")
        self.horizontalLayout_32.addWidget(self.label_98)
        self.lne_nro_acta_Renuncia = QtWidgets.QLineEdit(self.tab_4)
        self.lne_nro_acta_Renuncia.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_nro_acta_Renuncia.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_nro_acta_Renuncia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_acta_Renuncia.setObjectName("lne_nro_acta_Renuncia")
        self.horizontalLayout_32.addWidget(self.lne_nro_acta_Renuncia)
        self.boton_actualizar_renuncia = QtWidgets.QPushButton(self.tab_4)
        self.boton_actualizar_renuncia.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_renuncia.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_renuncia.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"color: rgb(0, 0, 0);")
        self.boton_actualizar_renuncia.setObjectName("boton_actualizar_renuncia")
        self.horizontalLayout_32.addWidget(self.boton_actualizar_renuncia)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.line_10 = QtWidgets.QFrame(self.tab_4)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_3.addWidget(self.line_10)
        self.label_51 = QtWidgets.QLabel(self.tab_4)
        self.label_51.setStyleSheet("font: 12pt \"Courier 10 Pitch\";\n"
"text-decoration: underline;")
        self.label_51.setObjectName("label_51")
        self.verticalLayout_3.addWidget(self.label_51)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_101 = QtWidgets.QLabel(self.tab_4)
        self.label_101.setObjectName("label_101")
        self.horizontalLayout_33.addWidget(self.label_101)
        self.dte_fec_exclusion = QtWidgets.QDateEdit(self.tab_4)
        self.dte_fec_exclusion.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_fec_exclusion.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_fec_exclusion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_exclusion.setObjectName("dte_fec_exclusion")
        self.horizontalLayout_33.addWidget(self.dte_fec_exclusion)
        self.label_100 = QtWidgets.QLabel(self.tab_4)
        self.label_100.setObjectName("label_100")
        self.horizontalLayout_33.addWidget(self.label_100)
        self.lne_nro_acta_exclusion = QtWidgets.QLineEdit(self.tab_4)
        self.lne_nro_acta_exclusion.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_nro_acta_exclusion.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_nro_acta_exclusion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_acta_exclusion.setObjectName("lne_nro_acta_exclusion")
        self.horizontalLayout_33.addWidget(self.lne_nro_acta_exclusion)
        self.boton_actualizar_exclusion = QtWidgets.QPushButton(self.tab_4)
        self.boton_actualizar_exclusion.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_exclusion.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_exclusion.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"color: rgb(0, 0, 0);")
        self.boton_actualizar_exclusion.setObjectName("boton_actualizar_exclusion")
        self.horizontalLayout_33.addWidget(self.boton_actualizar_exclusion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_33)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_95 = QtWidgets.QLabel(self.tab_8)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_35.addWidget(self.label_95)
        self.dte_fec_capitalizacion = QtWidgets.QDateEdit(self.tab_8)
        self.dte_fec_capitalizacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_capitalizacion.setObjectName("dte_fec_capitalizacion")
        self.horizontalLayout_35.addWidget(self.dte_fec_capitalizacion)
        self.label_96 = QtWidgets.QLabel(self.tab_8)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_35.addWidget(self.label_96)
        self.lne_importe_capitaliza = QtWidgets.QLineEdit(self.tab_8)
        self.lne_importe_capitaliza.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_importe_capitaliza.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_importe_capitaliza.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_importe_capitaliza.setObjectName("lne_importe_capitaliza")
        self.horizontalLayout_35.addWidget(self.lne_importe_capitaliza)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem26)
        self.boton_agregar_capitaliza = QtWidgets.QPushButton(self.tab_8)
        self.boton_agregar_capitaliza.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_agregar_capitaliza.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_agregar_capitaliza.setStyleSheet("background-color: rgb(140, 189, 58);")
        self.boton_agregar_capitaliza.setObjectName("boton_agregar_capitaliza")
        self.horizontalLayout_35.addWidget(self.boton_agregar_capitaliza)
        self.gridLayout_5.addLayout(self.horizontalLayout_35, 0, 0, 1, 1)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_110 = QtWidgets.QLabel(self.tab_8)
        self.label_110.setObjectName("label_110")
        self.horizontalLayout_63.addWidget(self.label_110)
        self.lne_nro_acta_capitaliza = QtWidgets.QLineEdit(self.tab_8)
        self.lne_nro_acta_capitaliza.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_nro_acta_capitaliza.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_nro_acta_capitaliza.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_acta_capitaliza.setObjectName("lne_nro_acta_capitaliza")
        self.horizontalLayout_63.addWidget(self.lne_nro_acta_capitaliza)
        self.label_111 = QtWidgets.QLabel(self.tab_8)
        self.label_111.setObjectName("label_111")
        self.horizontalLayout_63.addWidget(self.label_111)
        self.dte_fec_acta_capitaliza = QtWidgets.QDateEdit(self.tab_8)
        self.dte_fec_acta_capitaliza.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_fec_acta_capitaliza.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_fec_acta_capitaliza.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_acta_capitaliza.setObjectName("dte_fec_acta_capitaliza")
        self.horizontalLayout_63.addWidget(self.dte_fec_acta_capitaliza)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem27)
        self.gridLayout_5.addLayout(self.horizontalLayout_63, 1, 0, 1, 1)
        self.tw_historia_capitaliza = QtWidgets.QTableWidget(self.tab_8)
        self.tw_historia_capitaliza.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tw_historia_capitaliza.setObjectName("tw_historia_capitaliza")
        self.tw_historia_capitaliza.setColumnCount(5)
        self.tw_historia_capitaliza.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(191, 220, 173))
        self.tw_historia_capitaliza.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(191, 220, 173))
        self.tw_historia_capitaliza.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(191, 220, 173))
        self.tw_historia_capitaliza.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(191, 220, 173))
        self.tw_historia_capitaliza.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(177, 215, 154))
        self.tw_historia_capitaliza.setHorizontalHeaderItem(4, item)
        self.tw_historia_capitaliza.horizontalHeader().setDefaultSectionSize(150)
        self.tw_historia_capitaliza.horizontalHeader().setMinimumSectionSize(150)
        self.gridLayout_5.addWidget(self.tw_historia_capitaliza, 2, 0, 1, 1)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem28)
        self.boton_limpiar_5 = QtWidgets.QPushButton(self.tab_8)
        self.boton_limpiar_5.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_limpiar_5.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_limpiar_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(140, 189, 58);")
        self.boton_limpiar_5.setObjectName("boton_limpiar_5")
        self.horizontalLayout_36.addWidget(self.boton_limpiar_5)
        self.boton_actualizar_capitali = QtWidgets.QPushButton(self.tab_8)
        self.boton_actualizar_capitali.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_capitali.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_actualizar_capitali.setStyleSheet("background-color: rgb(140, 189, 58);\n"
"color: rgb(0, 0, 0);")
        self.boton_actualizar_capitali.setObjectName("boton_actualizar_capitali")
        self.horizontalLayout_36.addWidget(self.boton_actualizar_capitali)
        self.gridLayout_5.addLayout(self.horizontalLayout_36, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayout_7.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(form_asociado_actualizar)
        self.tabWidget.setCurrentIndex(1)
        self.boton_limpiar.clicked.connect(self.lne_correo.clear)
        self.boton_limpiar.clicked.connect(self.lne_tel_otro.clear)
        self.boton_limpiar.clicked.connect(self.lne_tel_principal.clear)
        self.boton_limpiar.clicked.connect(self.lne_provincia.clear)
        self.boton_limpiar.clicked.connect(self.lne_localidad.clear)
        self.boton_limpiar.clicked.connect(self.lne_depto.clear)
        self.boton_limpiar.clicked.connect(self.lne_bloque.clear)
        self.boton_limpiar.clicked.connect(self.lne_mzna.clear)
        self.boton_limpiar.clicked.connect(self.lne_c_postal.clear)
        self.boton_limpiar.clicked.connect(self.lne_domicilio.clear)
        self.boton_limpiar.clicked.connect(self.lne_nro_dom.clear)
        self.boton_limpiar.clicked.connect(self.lne_piso_domicilio.clear)
        self.boton_limpiar.clicked.connect(self.lne_nro_doc.clear)
        self.boton_limpiar.clicked.connect(self.lne_nro_cuil.clear)
        self.boton_limpiar.clicked.connect(self.lne_apellido_2.clear)
        self.boton_limpiar.clicked.connect(self.lne_nombre_2.clear)
        self.boton_limpiar.clicked.connect(self.lne_nro_acta_ca.clear)
        self.boton_limpiar.clicked.connect(self.lne_nro_foja.clear)
        self.boton_limpiar.clicked.connect(self.lne_nro_asoc.clear)
        self.boton_limpiar_5.clicked.connect(self.lne_nro_acta_capitaliza.clear)
        self.boton_limpiar_5.clicked.connect(self.lne_importe_capitaliza.clear)
        QtCore.QMetaObject.connectSlotsByName(form_asociado_actualizar)

    def retranslateUi(self, form_asociado_actualizar):
        _translate = QtCore.QCoreApplication.translate
        form_asociado_actualizar.setWindowTitle(_translate("form_asociado_actualizar", "ACTUALIZAR ASOCIADO"))
        self.label_12.setText(_translate("form_asociado_actualizar", "N° asociado:"))
        self.label_14.setText(_translate("form_asociado_actualizar", "Documento:"))
        self.boton_buscar.setText(_translate("form_asociado_actualizar", "BUSCAR"))
        self.label_6.setText(_translate("form_asociado_actualizar", "Documento:"))
        self.cbx_tipo_doc.setItemText(0, _translate("form_asociado_actualizar", "DNI"))
        self.cbx_tipo_doc.setItemText(1, _translate("form_asociado_actualizar", "LC"))
        self.cbx_tipo_doc.setItemText(2, _translate("form_asociado_actualizar", "LE"))
        self.cbx_tipo_doc.setItemText(3, _translate("form_asociado_actualizar", "CI"))
        self.label_5.setText(_translate("form_asociado_actualizar", "Estado civíl:"))
        self.cbx_estado_civil.setItemText(0, _translate("form_asociado_actualizar", "SOLTERA/O"))
        self.cbx_estado_civil.setItemText(1, _translate("form_asociado_actualizar", "CASADA/O"))
        self.cbx_estado_civil.setItemText(2, _translate("form_asociado_actualizar", "DIVORCIADA/O"))
        self.cbx_estado_civil.setItemText(3, _translate("form_asociado_actualizar", "VIUDA/O"))
        self.cbx_estado_civil.setItemText(4, _translate("form_asociado_actualizar", "CONCUBINA/O"))
        self.label_8.setText(_translate("form_asociado_actualizar", "CUIT / CUIL:"))
        self.label_28.setText(_translate("form_asociado_actualizar", "Localidad:"))
        self.label_29.setText(_translate("form_asociado_actualizar", "Provincia:"))
        self.label_7.setText(_translate("form_asociado_actualizar", "Fecha de nacimiento:"))
        self.dte_fec_nac.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_10.setText(_translate("form_asociado_actualizar", "Domicilio:"))
        self.label_11.setText(_translate("form_asociado_actualizar", "N°:"))
        self.label_23.setText(_translate("form_asociado_actualizar", "Piso:"))
        self.label_4.setText(_translate("form_asociado_actualizar", "Apellido y nombre:"))
        self.label_15.setText(_translate("form_asociado_actualizar", "Estado:"))
        self.cbx_estado_asoc.setItemText(0, _translate("form_asociado_actualizar", "ACTIVO"))
        self.cbx_estado_asoc.setItemText(1, _translate("form_asociado_actualizar", "RENUNCIA"))
        self.cbx_estado_asoc.setItemText(2, _translate("form_asociado_actualizar", "SUSPENDIDO"))
        self.cbx_estado_asoc.setItemText(3, _translate("form_asociado_actualizar", "EXPULSADO"))
        self.label_30.setText(_translate("form_asociado_actualizar", "Telefono principal:"))
        self.label_31.setText(_translate("form_asociado_actualizar", "Telefono secundario:"))
        self.label_32.setText(_translate("form_asociado_actualizar", "Correo electrónico:"))
        self.boton_actualizar.setText(_translate("form_asociado_actualizar", "ACTUALIZAR"))
        self.boton_limpiar.setText(_translate("form_asociado_actualizar", "LIMPIAR"))
        self.label_24.setText(_translate("form_asociado_actualizar", "Dpto:"))
        self.label_25.setText(_translate("form_asociado_actualizar", "Bloque:"))
        self.label_26.setText(_translate("form_asociado_actualizar", "Mzna:"))
        self.label_27.setText(_translate("form_asociado_actualizar", "C.Postal:"))
        self.label_2.setText(_translate("form_asociado_actualizar", "Fecha ingreso:"))
        self.dte_ingreso.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_3.setText(_translate("form_asociado_actualizar", "N° Acta C.A:"))
        self.label.setText(_translate("form_asociado_actualizar", "N° asociado:"))
        self.label_9.setText(_translate("form_asociado_actualizar", "N° Foja:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_asociado_actualizar", "Datos personales"))
        self.label_33.setText(_translate("form_asociado_actualizar", "Capital suscipto"))
        self.boton_actualizar_cap_suscripto.setText(_translate("form_asociado_actualizar", "Actualizar"))
        self.label_34.setText(_translate("form_asociado_actualizar", "Asamblea N°:"))
        self.label_35.setText(_translate("form_asociado_actualizar", "Fecha de asamblea:"))
        self.dte_fec_asamblea_cap_sus.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_36.setText(_translate("form_asociado_actualizar", "Cant. Cuotas Sociales:"))
        self.label_37.setText(_translate("form_asociado_actualizar", "Cant. de pesos:  $"))
        self.label_38.setText(_translate("form_asociado_actualizar", "Cant. de pesos en letras:"))
        self.label_39.setText(_translate("form_asociado_actualizar", "Integración de capital:"))
        self.boton_act_cap_integracion.setText(_translate("form_asociado_actualizar", "Actualizar"))
        self.label_40.setText(_translate("form_asociado_actualizar", "N°de cuota:"))
        self.label_41.setText(_translate("form_asociado_actualizar", "Fecha :"))
        self.dte_fec_cuota.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_42.setText(_translate("form_asociado_actualizar", "Pesos:"))
        self.btn_pagar.setText(_translate("form_asociado_actualizar", "Pagar"))
        self.label_43.setText(_translate("form_asociado_actualizar", "Tipo de aporte:"))
        self.cbx_aporte_tipo.setItemText(0, _translate("form_asociado_actualizar", "efectivo"))
        self.cbx_aporte_tipo.setItemText(1, _translate("form_asociado_actualizar", "especie"))
        self.boton_agregar.setText(_translate("form_asociado_actualizar", "AGREGAR"))
        item = self.tw_integracion_cap.horizontalHeaderItem(0)
        item.setText(_translate("form_asociado_actualizar", "N° cuota"))
        item = self.tw_integracion_cap.horizontalHeaderItem(1)
        item.setText(_translate("form_asociado_actualizar", "Fecha"))
        item = self.tw_integracion_cap.horizontalHeaderItem(2)
        item.setText(_translate("form_asociado_actualizar", "Pesos"))
        item = self.tw_integracion_cap.horizontalHeaderItem(3)
        item.setText(_translate("form_asociado_actualizar", "Tipo de aporte"))
        item = self.tw_integracion_cap.horizontalHeaderItem(4)
        item.setText(_translate("form_asociado_actualizar", "id"))
        item = self.tw_integracion_cap.horizontalHeaderItem(5)
        item.setText(_translate("form_asociado_actualizar", "estado"))
        self.label_44.setText(_translate("form_asociado_actualizar", "TRANSFERENCIA DE CUOTAS A:"))
        self.label_45.setText(_translate("form_asociado_actualizar", "CANT. CUOTAS:"))
        self.label_46.setText(_translate("form_asociado_actualizar", "MONTO EN $:"))
        self.label_47.setText(_translate("form_asociado_actualizar", "FECHA:"))
        self.dte_fec_transf.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_48.setText(_translate("form_asociado_actualizar", "N° ACTA C.A:"))
        self.boton_guardar_transferencia_2.setText(_translate("form_asociado_actualizar", "GUARDAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("form_asociado_actualizar", "Capital"))
        self.label_49.setText(_translate("form_asociado_actualizar", "SUSPENCIONES"))
        self.boton_guardar_suspenciones.setText(_translate("form_asociado_actualizar", "Actualizar"))
        self.label_52.setText(_translate("form_asociado_actualizar", "FECHA:"))
        self.dte_fec_susp.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_53.setText(_translate("form_asociado_actualizar", "N° ACTA:"))
        self.label_54.setText(_translate("form_asociado_actualizar", "DETALLE:"))
        self.boton_agregar_suspensiones.setText(_translate("form_asociado_actualizar", "AGREGAR"))
        item = self.tw_historia_susp.horizontalHeaderItem(0)
        item.setText(_translate("form_asociado_actualizar", "FECHA"))
        item = self.tw_historia_susp.horizontalHeaderItem(1)
        item.setText(_translate("form_asociado_actualizar", "N° ACTA"))
        item = self.tw_historia_susp.horizontalHeaderItem(2)
        item.setText(_translate("form_asociado_actualizar", "DETALLE"))
        item = self.tw_historia_susp.horizontalHeaderItem(3)
        item.setText(_translate("form_asociado_actualizar", "ID"))
        self.label_50.setText(_translate("form_asociado_actualizar", "RENUNCIA"))
        self.label_99.setText(_translate("form_asociado_actualizar", "FECHA:"))
        self.dte_fec_renuncia.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_98.setText(_translate("form_asociado_actualizar", "N° ACTA:"))
        self.boton_actualizar_renuncia.setText(_translate("form_asociado_actualizar", "Actualizar"))
        self.label_51.setText(_translate("form_asociado_actualizar", "EXCLUSIÓN"))
        self.label_101.setText(_translate("form_asociado_actualizar", "FECHA:"))
        self.dte_fec_exclusion.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_100.setText(_translate("form_asociado_actualizar", "N° ACTA:"))
        self.boton_actualizar_exclusion.setText(_translate("form_asociado_actualizar", "Actualizar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("form_asociado_actualizar", "Observaciones"))
        self.label_95.setText(_translate("form_asociado_actualizar", "Fecha:"))
        self.dte_fec_capitalizacion.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        self.label_96.setText(_translate("form_asociado_actualizar", "Importe:  $"))
        self.boton_agregar_capitaliza.setText(_translate("form_asociado_actualizar", "Agregar"))
        self.label_110.setText(_translate("form_asociado_actualizar", "N° Acta:"))
        self.label_111.setText(_translate("form_asociado_actualizar", "Fecha acta:"))
        self.dte_fec_acta_capitaliza.setDisplayFormat(_translate("form_asociado_actualizar", "dd/MM/yyyy"))
        item = self.tw_historia_capitaliza.horizontalHeaderItem(0)
        item.setText(_translate("form_asociado_actualizar", "Fecha"))
        item = self.tw_historia_capitaliza.horizontalHeaderItem(1)
        item.setText(_translate("form_asociado_actualizar", "Importe"))
        item = self.tw_historia_capitaliza.horizontalHeaderItem(2)
        item.setText(_translate("form_asociado_actualizar", "N° Acta"))
        item = self.tw_historia_capitaliza.horizontalHeaderItem(3)
        item.setText(_translate("form_asociado_actualizar", "Fecha acta"))
        item = self.tw_historia_capitaliza.horizontalHeaderItem(4)
        item.setText(_translate("form_asociado_actualizar", "ID"))
        self.boton_limpiar_5.setText(_translate("form_asociado_actualizar", "LIMPIAR"))
        self.boton_actualizar_capitali.setText(_translate("form_asociado_actualizar", "Actualizar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("form_asociado_actualizar", "Capitalización"))

